version: '3.7'

services:
  client:
    build:
      context: ./client_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    env_file:
      - .env
    command: sh -c 'npm install;npm run env; ng serve --host ${HOST} --port ${PORT} --aot --proxy-config proxy.conf.js'
    ports:
      - '${PORT}:${PORT}'
      - '35728:35728'
    volumes:
      - './:/app'
